# Generated by Django 3.2.9 on 2021-11-25 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=20)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
