# Generated by Django 3.2.9 on 2021-11-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Priority',
            new_name='Priorities',
        ),
    ]
