# Generated by Django 3.2.9 on 2021-11-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_rename_priority_priorities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priorities',
        ),
    ]
