# Generated by Django 3.2.9 on 2021-11-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_priorities'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorities',
            name='priority_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.priorities'),
        ),
    ]
